//-----------------------------------------------------------------------------
// CP250x_Configuration.h
//-----------------------------------------------------------------------------
// Copyright 2010 Silicon Laboratories, Inc.
// http://www.silabs.com
//
// Target: CP2501
//
// Tool chain: Raisonance
//
// Header file for CP250x_Configuration.h
//
// This file is dynamically generated by the CP250x Configuration Wizard.
// Only the APPLICATION_VERSION #defines should be edited
//

#ifndef _CP250X_CONFIGURATION_H_
#define _CP250X_CONFIGURATION_H_

//-----------------------------------------------------------------------------
// Header Files
//-----------------------------------------------------------------------------

#include "compiler_defs.h"

//-----------------------------------------------------------------------------
// Constant Definitions
//-----------------------------------------------------------------------------

#define  APPLICATION_VERSION_MSB          0x01        // Firmware Version BCD High
#define  APPLICATION_VERSION_LSB          0x00        // Firmware Version BCD Low

#define  VALIDATION_SIGNATURE_MSB         0x3D
#define  VALIDATION_SIGNATURE_LSB         0xC2

#define  TOUCH_MAX_COUNT                  0x02
#define  PEN_MAX_COUNT                    0x00

#define  LOCK_BYTE                        0xFF                 // Set to 0x00 to lock user space

// Configuration Report IDs
#define  ID_GETSET_USB_CONTROL            0x40
#define  ID_MOUSE_DATA                    0x80
#define  ID_TOUCH_DATA                    0x81
#define  ID_PEN_DATA                      0x82
#define  ID_GETSET_TOUCH_CONFIGURATION    0x83
#define  ID_GET_TOUCH_MAX_COUNT           0x84
#define  ID_GETSET_PEN_CONFIGURATION      0x85
#define  ID_GET_PEN_MAX_COUNT             0x86

#define  SIZE_GETSET_TOUCH_CONFIGURATION  0x02
#define  SIZE_GETSET_PEN_CONFIGURATION    0x02
#define  SIZE_GETSET_USB_CONTROL          0x3F
#define  SIZE_MOUSE_DATA                  0x05
#define  SIZE_TOUCH_DATA                  0x06
#define  SIZE_PEN_DATA                    0x06

// Feature Report Sizes (Bootloader Required)
#define  ID_SET_RESET_DEVICE              0x10
#define  ID_GET_BL_VER                    0x11
#define  ID_GET_APP_VER                   0x12
#define  ID_GET_SET_BL_MODE               0x14
#define  SIZE_SET_RESET_DEVICE            0x00
#define  SIZE_GET_BL_VER                  0x02
#define  SIZE_GET_APP_VER                 0x02
#define  SIZE_GET_SET_BL_MODE             0x01

// Screen Size
#define  X_RES_MSB                        0x05
#define  X_RES_LSB                        0x00
#define  Y_RES_MSB                        0x04
#define  Y_RES_LSB                        0x00

//-----------------------------------------------------------------------------
// Typedef Definitions
//-----------------------------------------------------------------------------

typedef struct
{
   U8  Mouse_Data_ID;
   U8  Mouse_Data_Length;
   U8  Touch_Data_ID;
   U8  Touch_Data_Length;
   U8  Pen_Data_ID;
   U8  Pen_Data_Length;
   U8  Touch_Max_Count_ID;
   U8  Touch_Max_Count;
   U8  Touch_Device_Mode_Configuration_ID;
   U8  Pen_Max_Count_ID;
   U8  Pen_Max_Count;
   U8  Pen_Device_Mode_Configuration_ID;
   U8  USB_Control_ID;
} CP250x_Capabilities_Structure;

extern code CP250x_Capabilities_Structure CP250x_Capabilities;

#endif   // _CP250X_CONFIGURATION_H_

//-----------------------------------------------------------------------------
// End Of File
//-----------------------------------------------------------------------------