//-----------------------------------------------------------------------------
// CP250x_BUFFER_STRUCT_API.h
//-----------------------------------------------------------------------------
// Copyright 2010 Silicon Laboratories, Inc.
// http://www.silabs.com
//
// Target: CP2501
//
// Tool chain: Raisonance
//
// Contains structures which describe the format of USB data.  The user
// firmware should use these structures to determine how to format the data
// in the USB_Position_Buffer[].
//
// This file is dynamically generated by the CP250x Configuration Wizard.
// Do not edit this file.
//

#ifndef _CP250X_BUFFER_STRUCT_H_
#define _CP250X_BUFFER_STRUCT_H_

//-----------------------------------------------------------------------------
// Header Files
//-----------------------------------------------------------------------------

#include "compiler_defs.h"

//-----------------------------------------------------------------------------
// Constant Definitions
//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
// Typedef Definitions
//-----------------------------------------------------------------------------

// This is the structure of the data format for a touch point.
typedef struct
{
   U8    Controls;           // Tip Switch, In Range
   U8    Contact_Identifier;
   UU16  X;
   UU16  Y;
} CP250x_Touch_Structure;

// This structure defines the buffer space for the mouse data.
typedef struct
{
   U8    Controls;           // Includes Mouse button
   UU16  X;
   UU16  Y;
} CP250x_Mouse_Structure;

#define  MOUSE_BUTTON_1    0x01
#endif   // _CP250X_BUFFER_STRUCT_H_

//-----------------------------------------------------------------------------
// End Of File
//-----------------------------------------------------------------------------

