//-----------------------------------------------------------------------------
// CP250x_Configuration.c
//-----------------------------------------------------------------------------
// Copyright 2010 Silicon Laboratories, Inc.
// http://www.silabs.com
//
// Target: CP2501
//
// Tool chain: Raisonance
//
// Contains configuration information for HID reports and application signature
//
// This file is statically generated by the CP250x Configuration Wizard.
// Do not edit this file.

//-----------------------------------------------------------------------------
// Header Files
//-----------------------------------------------------------------------------

#include "compiler_defs.h"
#include "CP250x_API.h"
#include "CP250x_Buffer_Struct.h"
#include "CP250x_Configuration.h"

//-----------------------------------------------------------------------------
// Global Variables
//-----------------------------------------------------------------------------
code CP250x_Capabilities_Structure CP250x_Capabilities =
{
   ID_MOUSE_DATA,                   // Mouse Report ID
   SIZE_MOUSE_DATA,                 // Mouse Report Length
   ID_TOUCH_DATA,                   // Touch Report ID
   SIZE_TOUCH_DATA,                 // Touch Report Length
   ID_PEN_DATA,                     // Pen Report ID
   SIZE_PEN_DATA,                   // Pen Report Length
   ID_GET_TOUCH_MAX_COUNT,          // Maximum Touch Count Report ID
   TOUCH_MAX_COUNT,                 // Maximum Number of Touch Points
   ID_GETSET_TOUCH_CONFIGURATION,   // Touch Device Mode Configuration Report ID
   ID_GET_PEN_MAX_COUNT,            // Maximum Pen Count Report ID
   PEN_MAX_COUNT,                   // Maximum Number of Pen Points
   ID_GETSET_PEN_CONFIGURATION,     // Pen Device Mode Configuration Report ID
   ID_GETSET_USB_CONTROL            // Vendor Control ID
};

// Application Version defined in CP250x_Configuration.h
code U8 ApplicationVersionMSB  =  APPLICATION_VERSION_MSB;
code U8 ApplicationVersionLSB  =  APPLICATION_VERSION_LSB;

// Validation Signature defined in CP250x_Configuration.h
code U8 ValidationSignatureMSB  =  VALIDATION_SIGNATURE_MSB;
code U8 ValidationSignatureLSB  =  VALIDATION_SIGNATURE_LSB;

//-----------------------------------------------------------------------------
// End Of File
//-----------------------------------------------------------------------------